---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app certificates-import
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: cert-manager
      namespace: cert-manager
  interval: 1h
  path: ./k8s/apps/network/certificates/import
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  # The first issuance creates the remote 1Password item consumed above.
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app certificates-export
  namespace: &namespace network
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: certificates-import
      namespace: network
    - name: cert-manager
      namespace: cert-manager
    - name: external-secrets
      namespace: external-secrets
  interval: 1h
  path: ./k8s/apps/network/certificates/export
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: cbannister-xyz
      namespace: *namespace
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: rociobolanos-com
      namespace: *namespace
  wait: false
