---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-pushover
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .API_KEY }}"
        USER_KEY: "{{ .USER_KEY }}"
  dataFrom:
    - extract:
        key: pushover
