---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanrr
  annotations:
    reloader.stakater.com/auto: "true"
  labels: &labels
    app.kubernetes.io/instance: cleanrr
    app.kubernetes.io/name: cleanrr
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *labels
    spec:
      automountServiceAccountToken: false
      containers:
        - name: cleanrr
          image: ghcr.io/zariel/cleanrr:v0.1.3@sha256:37dd9fd5d4980e4ee2d849aab84e91b97d750bbb81512fbb12dad2247a676bef
          imagePullPolicy: IfNotPresent
          env:
            - name: CLEANRR_SERVERS__RADARR__URL
              value: http://radarr
            - name: CLEANRR_SERVERS__SONARR__URL
              value: http://sonarr
          envFrom:
            - secretRef:
                name: cleanrr-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            failureThreshold: 30
            periodSeconds: 10
            httpGet:
              path: /health/startup
              port: http
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /health/live
              port: http
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /health/ready
              port: http
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
