[paths]
media_dirs = ["/data/media/tv", "/data/media/films"]

[server]
bind = "0.0.0.0:2468"

[torrent_clients.qbit_main]
kind = "qbittorrent"
url = "http://qbittorrent.default.svc.cluster.local"
default_save_path = "/data/torrents/complete"
default_category = "cross-seed"
default_tags = ["cross-seed", "sporos"]

[indexers.prowlarr.main]
url = "http://prowlarr.default.svc.cluster.local"

[indexers.arr.sonarr.main]
url = "http://sonarr.default.svc.cluster.local"

[indexers.arr.radarr.main]
url = "http://radarr.default.svc.cluster.local"

[matching]
include_single_episodes = true

[injection]
dry_run = true
link_type = "hardlink"
link_dirs = [
  "/data/downloads/torrents/complete/cross-seed",
  "/data/downloads/torrents/complete/music/cross-seed",
]

[injection.recheck]
skip_recheck = true
ignore_non_relevant_files_to_resume = true
