---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - deployment.yaml
  - httproute.yaml
  - service.yaml
configMapGenerator:
  - name: znc-custom-init
    files:
      - disable-protected-web-sessions.sh=resources/disable-protected-web-sessions.sh
generatorOptions:
  disableNameSuffixHash: true
