apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  labels:
    app: thelounge
spec:
  selector:
    matchLabels:
      app: thelounge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thelounge
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      hostname: thelounge
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: thelounge
        - name: cluster-ca-certificates
          configMap:
            name: cluster-ca-certificates.crt
            items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000]
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: thelounge
          image: ghcr.io/thelounge/thelounge:4.5.2@sha256:c764151188d2c805932856ece9673917c868be38e22486d4fd9c5c376c663790
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
            - name: THELOUNGE_HOME
              value: /config/thelounge
            - name: SQLITE_TMPDIR
              value: /config/thelounge/_tmp
            - name: NODE_EXTRA_CA_CERTS
              value: /etc/ssl/certs/cluster-ca-certificates.crt
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
          ports:
            - containerPort: 9000
              name: web
          startupProbe:
            httpGet:
              path: /
              port: web
          livenessProbe:
            httpGet:
              path: /
              port: web
          readinessProbe:
            httpGet:
              path: /
              port: web
            successThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cluster-ca-certificates
              mountPath: /etc/ssl/certs/cluster-ca-certificates.crt
              subPath: ca-certificates.crt
              readOnly: true
