---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trust-manager
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.25.0
  url: oci://quay.io/jetstack/charts/trust-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app trust-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: trust-manager
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    app:
      metrics:
        service:
          servicemonitor:
            enabled: true
            interval: 1m
    crds:
      enabled: true
      keep: true
    defaultPackageImage:
      repository: quay.io/jetstack/trust-pkg-debian-bookworm
      tag: "20230311.0"
    secretTargets:
      enabled: true
      authorizedSecrets:
        - cluster-ca-secret
        - operator-ca-tls-cluster-ca
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
