---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sporos
  annotations:
    reloader.stakater.com/auto: "true"
  labels: &labels
    app.kubernetes.io/component: sporos
    app.kubernetes.io/instance: sporos
    app.kubernetes.io/name: sporos
spec:
  selector:
    matchLabels: *labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *labels
    spec:
      priorityClassName: cluster-p1
      terminationGracePeriodSeconds: 60
      containers:
        - name: sporos
          image: ghcr.io/zariel/sporos:0.0.4@sha256:80f149fc8f6ac38b0ce619446c9520ab3b00f01c27a8d1dada2fdcfb8341a038
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/London
          envFrom:
            - secretRef:
                name: sporos-secret
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            failureThreshold: 30
            periodSeconds: 10
            httpGet:
              path: /livez
              port: http
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /livez
              port: http
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /readyz
              port: http
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: state
            - mountPath: /media
              name: arr-media
            - mountPath: /config/sporos.toml
              name: config-file
              readOnly: true
              subPath: config.toml
      enableServiceLinks: false
      initContainers:
        - name: prepare-link-dirs
          image: docker.io/library/busybox:1.38.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - install -d -m 0770 /media/downloads/torrents/complete/sporos && chgrp 3005 /media/downloads/torrents/complete/sporos
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
          volumeMounts:
            - mountPath: /media
              name: arr-media
      restartPolicy: Always
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 3005
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: sporos
        - name: arr-media
          nfs:
            server: nas.cbannister.casa
            path: /mnt/bighorse/arr
        - name: config-file
          configMap:
            name: sporos-config
