---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sporos
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sporos-secret
    template:
      engineVersion: v2
      data:
        SPOROS__SERVER__API_TOKEN: "{{ .CROSS_SEED_API_KEY }}"
        SPOROS__INDEXERS__PROWLARR__MAIN__API_KEY: "{{ .PROWLARR_API_KEY }}"
        SPOROS__INDEXERS__ARR__RADARR__MAIN__API_KEY: "{{ .RADARR_API_KEY }}"
        SPOROS__INDEXERS__ARR__SONARR__MAIN__API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
