---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sporos
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 10s
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: sporos
