---
cluster:
  etcd:
    advertisedSubnets:
      - 10.254.1.0/31
      - 10.254.1.2/31
      - 10.254.1.4/31
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  intel.feature.node.kubernetes.io/gpu: "true"
  topology.kubernetes.io/region: homelab
  topology.kubernetes.io/zone: hollywoo
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
resources:
  requests:
    cpu: 1000m
    memory: 3Gi
  limits:
    cpu: 1000m
    memory: 4Gi
extraArgs:
  feature-gates: MutatingAdmissionPolicy=true
  runtime-config: admissionregistration.k8s.io/v1beta1=true
---
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    enabled: true
    conditions: []
---
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    - level: Metadata
---
apiVersion: v1alpha1
kind: KubeAdmissionControlConfig
name: PodSecurity
$patch: delete
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
resources:
  requests:
    cpu: 500m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 768Mi
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
extraArgs:
  bind-address: 0.0.0.0
config:
  apiVersion: kubescheduler.config.k8s.io/v1
  kind: KubeSchedulerConfiguration
  profiles:
    - schedulerName: default-scheduler
      plugins:
        score:
          disabled:
            - name: ImageLocality
      pluginConfig:
        - name: PodTopologySpread
          args:
            defaultingType: List
            defaultConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
allowedKubernetesNamespaces:
  - system-upgrade
