---
cache:
  enabled: true
  dir: /data/cache
  port: 8082
  proxy_port: 8081
container:
  docker_host: "-"
  workdir_parent: shared/workdir
host:
  workdir_parent: /data/act
log:
  level: info
plugins:
  k8s:
    address: "unix:///plugin/forgejo-runner-k8s.sock"
    options:
      namespace: forgejo-runners
      poll_timeout: 10m
runner:
  capacity: 2
  labels:
    - ubuntu-latest:k8s:///config/podspec-default.yaml
    - ubuntu-24.04:k8s:///config/podspec-default.yaml
    - default:k8s:///config/podspec-default.yaml
    - docker:k8s:///config/podspec-dind.yaml
  timeout: 3h
