apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: default
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:TFrxteMhlFVDTKwk4503voJqm+rxUzfp6aYWFURKKJvGyYSY76ZwLywtOClfaZBeEUwEKLuIH9dIhYpyfYeXLa1oPCxQzF499w0pwhQaQoJSvAKPjdYqPSCFDpjhft34fhwJwkMae5TUUbHABH00nxNYwpjhi535Lz72zJakE/s=,iv:ZF+N4rr3H1TkCSXgPws7TcJ5dSW8leNgnWvT3zwmyRk=,tag:S4Dl4F5niMWsKLBkFIODnA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:IViHGnfJcHgchBqqKGBnQeJCLY1Ktc1d8RSlLhulpaEqtV29MG9mOwPY0uvv/NYJ,iv:jNLPVPzMrVxohHfkw/P6c3Hxf5j2fxz/bWMsDRM5RgI=,tag:8AJjYDaWpzTFDqVclnsWJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNERod3ZiMjRJdFNQbDJM
            TGYwZzNBbTF5dkZ0OVU0eVRoazRSQklQeEhJClhIbndzck5PU3BTQVZqcFVnSjZ2
            SXZIVXlMOHFnbjhjN0M5VnNpQmMzOTQKLS0tIGl5WTJSMWZlYXp2N25SZ0tOeGJT
            c1RQRVNWZHZ3NHVvV2kzNjRuNHRTaVUKvJ27OeQ65Wl+PP1J3iCI62CKvKV85TXe
            NbiA12uwIa1BNZYH/jlbDMESbxijwVNoZlWehVJox3euTCYtWl2q0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:36:32Z"
    mac: ENC[AES256_GCM,data:4Fy7ICEHVwBpuo3wTpKB9EpLzh8SWyLIezMgPuZ8sBzIRAiKhURZak53UqX8n6uZ8v/M6Z4VNN7yGjvJ2ghtGqvtcjrPlDQ3QbOMwc1gxymvvJYv1AjXeHImMl5B2tt/2fKh40alHfX21UGBQBpWKt0jOKVxxGfzO6bL99U2asw=,iv:6qYKZSr+z0uDT1sIAFkIBQPPSN77FHoXdPxdk0ul0AQ=,tag:g45obX+af399cuVoevdu2w==,type:str]
    version: 3.13.3
