apiVersion: v1
kind: Secret
metadata:
    name: paperless-db
    namespace: default
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:JQO37kqiYj1EKM96cRxXe8GKyJcAnNSToROf9cXvnBr/EdLer6xAatEP++rS73tW,iv:cBgFQbywAOfqsWPMOinddSJt5+RQF6vzp+vnCPB9g1E=,tag:lZeGxjlEodQzOFVkrA4KeA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:9YtoTeSKFNYULQHU9fIwFMUADPnJudX5K1GVvu9m0CX0EgHBDlME4MwEeBob8Ndc,iv:CQR0nYCJcDurFjf4QkbCPm7FpHT4PJgYA/2swnGfOL0=,tag:N2GkgcZ32wskVs1+t2H+VQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:eobPl9glGPEv,iv:6f1RnVS4KKb7bZaixDbSj80ABLGikhU4p9yMDYMvN00=,tag:C0qXFPWwB8twQZ7o0qOeQQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:01UeQyF87I72,iv:7Bcx8eIed+I3MAk8WtWVm31mD1tAJnCyE+eXuv9v9+E=,tag:FqI9ePXdGL6LHCiEn0Roxw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:X67YuqREA/howEJVtgkEwzb2hmu01zMZj+yXDa+6TABUoFuo,iv:9plpUVjIO2n1FPercl4gR32YBClFI2Dd5pTUEI0l4OQ=,tag:HpNp9WtvuZc5BhB5BlkEFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWm16N2d0TnpxUWtTa0U5
            WXBVbmZCaUF3ZFArS1M2MnJQUzEvSURacWdzClRnVTBkLzM5b0RTaW1lSjk1NkM1
            ZXg1UElGUElDaFBocjQ4UXd5UDMrMGcKLS0tIFdnRHNSbHNJWXk0c0xVNXBtQVg3
            eUFhWUZ0Sk1xMWo5b3lKcWJFTnZKeDAKzoAvvzkSpZXiwsjVFaRbby0xismtYdBn
            97hDXpHyelpDgRTZljPplcqiNNmM2pZnuLz4/FdmhGqe/g+2oWZgMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:36:32Z"
    mac: ENC[AES256_GCM,data:is9HIUOTnwcEwJU+Ud/IJHayc1TDRX09B/Z+soct/oJfxCplRZb3Q5MiRD1OlJRlYtEgaI46JbtqnZKwyq2vGWl64mmaUs0Rt+J+QnDqvaqg31jvNPlfM36o/oFsVUKRL8hjY+Lmj4LmHHyORMBMC41qAmjnqK7GhQEkB0JWBOI=,iv:yP8IiMy/jVMasr49oancV5nc923GDjobfPQXSaie//s=,tag:Lng9yKEkwHdPAA2ur/+GhA==,type:str]
    version: 3.13.3
