---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-initdb
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-initdb
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vc
        property: password
