apiVersion: v1
kind: Secret
metadata:
    name: paperless-valkey
    namespace: default
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:joLoF/kUDYfW8gxM9l2QqF1NgbCXbqIQ2EehcMNapSVTGK3+J6myMiz/VYLig97S,iv:efiLaDKv2UEUT3cm41H4qmR/k5OD1Vc/t77wAaqKX9Y=,tag:79/W4Ky19F3OOaKRiUkAMg==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:RJkA43d2jkAj879kkiFc+LioxAKN3dbvv9HZrbBqXTyUt6UhXuN9F9OwFKOj0bCsxBQgsW1kS+ffabE3N6wIHZP1hi7iUcQ4mXtlAaEVlzla+jZgD4cf2l5JAIheo7sueeh+gLl8XF3X,iv:qTkSs4PBBpw0qT86IsZObvIULSil1U/AYZ/YqvB2Hlc=,tag:/jibuVjegP4gXd8fKf+Ldg==,type:str]
    valkey.conf: ENC[AES256_GCM,data:6qWsg/O6+riqUCAZru0qAsPzmoe2FXIAJv9yr0KGA8uvqmkF5PWXgiCCrwOQ4MQgjM2FdhovxMMfuDeA8ZA1IPwUl5zKoUIsYkB8YbRE/DUKlNXyD00ezMcL2FFNv2u05KAG998mK9go+mbMqxH95lq4AlxtM8GeSDievz8OM0NFPR6fj/Dy7S21uCppH2dwxJPCL+FMHqb2bg9/ylfv,iv:APRwE+CAXocsosSjdD/kDG83zPfHwQxJjPJ3FzSqleo=,tag:RH36VCJmpwf8jBXZXYAtJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRjJ1WHNIS1VJdmVhaE0v
            S09nM1RwK0dydEF6YlgyRU9yWU5UdDdlWXpNCis4YWpGcUlQWmd0UVBOSi9PWnd2
            ck1MLytTY0g5dC9nRURrUFdCOG92a3cKLS0tIHRJZGlEWlFDK0VGRkE5ZGJoTzVZ
            TlR4QU5lbWQwbVAxZUpQSC9tWjBWeWcKrkz3AKfQLITybzkr2tKKDF+5VyCkeGiC
            ZlIJLompVov0HsqMcS4rjKfk7Ake9ZPvmESM37L3El9yx348idwdqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1865axnecqy9eccq9fzhpwkz3nkf0sxfeurva6rquyktplhzssv2s32kv5w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T16:36:32Z"
    mac: ENC[AES256_GCM,data:XfHs7lT77sGyTAgAxh0Rby0IY8kROmSMfC6sJfNNwtpvPmafwBLEQrPYcYUmMd4zEzdgKx9ekOtQF3uylCbMPUCuh4kM0ErPLcn1B+5JHKIWvlVL8edyXkjzBrdhAX8V/XArcmzn4hBTb/RnWeBlI86HJO2o0A66/Xf0BZ1Gb6k=,iv:QfLW9kKi9V6X8kHBA2WLFBTcjze6a6oCNfEZ+qpGLx0=,tag:Lni/IJ6Loe9Eapza5jFNtw==,type:str]
    version: 3.13.3
