apiVersion: katl.dev/v1alpha1
kind: ManagementIdentity
clusterName: hollywoo
createdAt: 2026-09-20T10:32:17.432185394Z
certificateAuthority:
    certificate: |
        -----BEGIN CERTIFICATE-----
        MIIBRjCB+aADAgECAhEAnpD/9zi5uJ03T6xMANTjBzAFBgMrZXAwIzEhMB8GA1UE
        AxMYa2F0bCBtYW5hZ2VtZW50IGhvbGx5d29vMB4XDTI2MDkyMDEwMjcxN1oXDTM2
        MDkyMDEwMzIxN1owIzEhMB8GA1UEAxMYa2F0bCBtYW5hZ2VtZW50IGhvbGx5d29v
        MCowBQYDK2VwAyEAODKmX3T5QZtuEK03YF3vvkbZD4ud5Z0zEEb1BG264yajQjBA
        MA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSo6aIr
        PgITkNc1PSJ0ROOkyb8r1jAFBgMrZXADQQAQ0cVM731jeMdpgJFa14uVtdKq+tZk
        ogr4PCKfOX0FIbqqUEysegB+yhVFEHKdd08ljHFa9c6FtLrqn4hUJDcC
        -----END CERTIFICATE-----
    privateKey: |
        -----BEGIN PRIVATE KEY-----
        MC4CAQAwBQYDK2VwBCIEILrj7e2WsdRLdU3bGkF3a9BnFOE0UYxnjEUDepLTsyrw
        -----END PRIVATE KEY-----
operator:
    certificate: |
        -----BEGIN CERTIFICATE-----
        MIIBSDCB+6ADAgECAhBhr83FyKL6qBdw74kkZtQrMAUGAytlcDAjMSEwHwYDVQQD
        ExhrYXRsIG1hbmFnZW1lbnQgaG9sbHl3b28wHhcNMjYwOTIwMTAyNzE3WhcNMzYw
        OTIwMTAzMjE3WjASMRAwDgYDVQQDEwdrYXRsY3RsMCowBQYDK2VwAyEAbHweP9fH
        wgZ1IDSgta2KKnOixsnkPGCL1lVAhxGWqI6jVjBUMA4GA1UdDwEB/wQEAwIHgDAT
        BgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFKjp
        ois+AhOQ1zU9InRE46TJvyvWMAUGAytlcANBAA42rK2Qliwuk9QIHyR9MaJ3tKIk
        2uKyxvR2X32+/W0rj+ErD7Dai1YVPk0iEaybVS+BGoP+wIJzpteBCBvaBAc=
        -----END CERTIFICATE-----
    privateKey: |
        -----BEGIN PRIVATE KEY-----
        MC4CAQAwBQYDK2VwBCIEIOwIyYrA1srVOUn+7PdyI7F3CCkPnyTc8xo6H3Anf62B
        -----END PRIVATE KEY-----
nodes:
    k8s-0:
        certificate: |
            -----BEGIN CERTIFICATE-----
            MIIBWjCCAQygAwIBAgIRAO1k9KZ6mKUp3C03YkyI5SMwBQYDK2VwMCMxITAfBgNV
            BAMTGGthdGwgbWFuYWdlbWVudCBob2xseXdvbzAeFw0yNjA5MjAxMDI3MTdaFw0z
            NjA5MjAxMDMyMTdaMBAxDjAMBgNVBAMTBWs4cy0wMCowBQYDK2VwAyEAKAzS4+OC
            3NRToQlKD6rBOO9GqmAXc1qE2iS+rkE2+gqjaDBmMA4GA1UdDwEB/wQEAwIHgDAT
            BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFKjp
            ois+AhOQ1zU9InRE46TJvyvWMBAGA1UdEQQJMAeCBWs4cy0wMAUGAytlcANBADef
            Zx6YqgoIuhjwhX8X70Ob3ZwG2Sy1QPW9kZyfZ5uEdvgWHMaag8Crld4iQ5GxhsXc
            OEjVFLpN1ZNWoT9ZWgM=
            -----END CERTIFICATE-----
        privateKey: |
            -----BEGIN PRIVATE KEY-----
            MC4CAQAwBQYDK2VwBCIEIJWZBQiX4pme5B9Iuk2oLjB90wCPrXAQkIFW2p0k/wgs
            -----END PRIVATE KEY-----
    k8s-1:
        certificate: |
            -----BEGIN CERTIFICATE-----
            MIIBWjCCAQygAwIBAgIRAK4tbwj9yv70TZlFn8prAV0wBQYDK2VwMCMxITAfBgNV
            BAMTGGthdGwgbWFuYWdlbWVudCBob2xseXdvbzAeFw0yNjA5MjAxMDI3MTdaFw0z
            NjA5MjAxMDMyMTdaMBAxDjAMBgNVBAMTBWs4cy0xMCowBQYDK2VwAyEAiuG49rdF
            NYLTRK5cR+w/Y1J+CiUfX6zdsjcgx08WNHKjaDBmMA4GA1UdDwEB/wQEAwIHgDAT
            BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFKjp
            ois+AhOQ1zU9InRE46TJvyvWMBAGA1UdEQQJMAeCBWs4cy0xMAUGAytlcANBAOPG
            7R3QprbmkJXwSG347eWsJNP2IO3kob1OEX1Z5HJfkUGXY004qFtFj1Jcju4kBICk
            RWxL9CxU7WuqbdyFHwU=
            -----END CERTIFICATE-----
        privateKey: |
            -----BEGIN PRIVATE KEY-----
            MC4CAQAwBQYDK2VwBCIEIDFjl46dHQ+qCgquNfl9Ui0+vvdu4dy4Elq+cU57rEVo
            -----END PRIVATE KEY-----
    k8s-2:
        certificate: |
            -----BEGIN CERTIFICATE-----
            MIIBWTCCAQugAwIBAgIQVTbrFYZoTSSsZDLY94MH1zAFBgMrZXAwIzEhMB8GA1UE
            AxMYa2F0bCBtYW5hZ2VtZW50IGhvbGx5d29vMB4XDTI2MDkyMDEwMjcxN1oXDTM2
            MDkyMDEwMzIxN1owEDEOMAwGA1UEAxMFazhzLTIwKjAFBgMrZXADIQAXsDys7QAV
            r462ScC9CFoBcpZW3wNUFgsujDMWMB90bKNoMGYwDgYDVR0PAQH/BAQDAgeAMBMG
            A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUqOmi
            Kz4CE5DXNT0idETjpMm/K9YwEAYDVR0RBAkwB4IFazhzLTIwBQYDK2VwA0EArOiE
            Bz7xhzCi5vHPgSORTII6LZ1/SOSlY3x7XaeQpdyh25uN/CsKyJvdIGJ/fyhK71px
            rVdcH+NCy4Wf2e61Cw==
            -----END CERTIFICATE-----
        privateKey: |
            -----BEGIN PRIVATE KEY-----
            MC4CAQAwBQYDK2VwBCIEIHvUQMBHLJf2+7nog46dvDvlfeE/aH9MMlmBek6UgAIW
            -----END PRIVATE KEY-----
