---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-image-pull
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-image-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "git.cbannister.xyz": {
                "auth": "{{ printf "%s:%s" .USERNAME .IMAGE_PULL_SECRET | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: forgejo-image-pull
