---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vector-aggregator
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vector-aggregator
      app.kubernetes.io/name: vector
