apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  containers:
    - name: kube-scheduler
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
