---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: meilisearch-secret
    template:
      data:
        master_key: "{{ .MEILISEARCH_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: karakeep
