---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
spec:
  chartRef:
    kind: OCIRepository
    name: meilisearch
  interval: 30m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568

    controllers:
      meilisearch:
        forceRename: meilisearch
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            app.kubernetes.io/component: meilisearch
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.48.1@sha256:ad98ec0ab2a387da5c140fe9d935eadc6e3a42aee185b4249dfafd985fb49e1c
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: meilisearch-secret
                    key: master_key
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 4Gi

    service:
      app:
        forceRename: meilisearch
        primary: true
        controller: meilisearch
        ports:
          http:
            port: 7700

    persistence:
      data:
        existingClaim: meilisearch
        advancedMounts:
          meilisearch:
            app:
              - path: /meili_data
