apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 150
serializeImagePulls: false
allowedUnsafeSysctls:
  - net.ipv4.*
  - net.ipv6.*
seccompDefault: true
clusterDNS:
  - 172.21.0.10
clusterDomain: cluster.local
