---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.3
  policy:
    rebootMode: powercycle
  healthChecks:
    - apiVersion: v1
      kind: Pod
      namespace: kube-system
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: control-plane
          app.kubernetes.io/managed-by: Talos
          tier: control-plane
      description: Kubernetes control plane pods are healthy
      expr: |-
        status.phase == "Running" &&
        status.conditions.exists(c, c.type == "Ready" && c.status == "True") &&
        status.containerStatuses.all(c, c.ready == true)
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      expr: |-
        status.conditions.filter(c, c.type == "Synchronizing").all(c, c.status == "False")
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
